export const MOCK_SITES = [
  { id: 'S-101', name: 'Green Valley Farm', location: 'Punjab', area: '50 Acres', soilType: 'Loamy', status: 'Active' },
  { id: 'S-102', name: 'Sunrise Agro Fields', location: 'Haryana', area: '35 Acres', soilType: 'Sandy Loam', status: 'Active' },
  { id: 'S-103', name: 'Riverbank Plantation', location: 'Uttar Pradesh', area: '60 Acres', soilType: 'Alluvial', status: 'Active' },
  { id: 'S-104', name: 'Highland Crop Zone', location: 'Madhya Pradesh', area: '40 Acres', soilType: 'Silty Clay', status: 'Inactive' },
  { id: 'S-105', name: 'Eastern Harvest Land', location: 'Bihar', area: '28 Acres', soilType: 'Loamy', status: 'Active' },
  { id: 'S-106', name: 'Deccan Black Soil Hub', location: 'Maharashtra', area: '75 Acres', soilType: 'Black Regur', status: 'Active' },
  { id: 'S-107', name: 'Thar Edge Cultivation', location: 'Rajasthan', area: '120 Acres', soilType: 'Arid Sandy', status: 'Active' },
  { id: 'S-108', name: 'Nilgiri Tea Estates', location: 'Tamil Nadu', area: '85 Acres', soilType: 'Red Loamy', status: 'Active' },
  { id: 'S-109', name: 'Coastal Palm Grove', location: 'Kerala', area: '15 Acres', soilType: 'Laterite', status: 'Active' },
  { id: 'S-110', name: 'Brahmaputra Silt Farm', location: 'Assam', area: '45 Acres', soilType: 'Alluvial Silt', status: 'Active' },
  { id: 'S-111', name: 'Gujarat Cotton Belt', location: 'Gujarat', area: '90 Acres', soilType: 'Black Clayey', status: 'Active' },
  { id: 'S-112', name: 'Telangana Drylands', location: 'Telangana', area: '55 Acres', soilType: 'Red Sandy', status: 'Inactive' },
  { id: 'S-113', name: 'Odisha Paddy Fields', location: 'Odisha', area: '30 Acres', soilType: 'Clayey', status: 'Active' },
  { id: 'S-114', name: 'Chhota Nagpur Plot', location: 'Jharkhand', area: '22 Acres', soilType: 'Red and Yellow', status: 'Active' },
  { id: 'S-115', name: 'Himalayan Orchard', location: 'Himachal Pradesh', area: '12 Acres', soilType: 'Mountain Forest', status: 'Active' },
  { id: 'S-116', name: 'Doon Valley Acres', location: 'Uttarakhand', area: '18 Acres', soilType: 'Terai Soil', status: 'Active' },
  { id: 'S-117', name: 'Sundarban Delta Edge', location: 'West Bengal', area: '25 Acres', soilType: 'Saline Alluvial', status: 'Active' },
  { id: 'S-118', name: 'Malwa Plateau Site', location: 'Madhya Pradesh', area: '65 Acres', soilType: 'Medium Black', status: 'Active' },
  { id: 'S-119', name: 'Mysuru Silk Farms', location: 'Karnataka', area: '40 Acres', soilType: 'Red Loamy', status: 'Active' },
  { id: 'S-120', name: 'Zanskar Alpine Plot', location: 'Ladakh', area: '10 Acres', soilType: 'Glacial Lithic', status: 'Inactive' },
  { id: 'S-121', name: 'Godavari Basin North', location: 'Andhra Pradesh', area: '50 Acres', soilType: 'Deltaic Alluvial', status: 'Active' },
  { id: 'S-122', name: 'Raipur Plain Zone', location: 'Chhattisgarh', area: '48 Acres', soilType: 'Red Sandy', status: 'Active' },
  { id: 'S-123', name: 'Goan Cashew Hills', location: 'Goa', area: '20 Acres', soilType: 'Laterite', status: 'Active' },
  { id: 'S-124', name: 'Sikkim Organic Site', location: 'Sikkim', area: '8 Acres', soilType: 'Brown Forest', status: 'Active' },
  { id: 'S-125', name: 'Imphal Valley Farm', location: 'Manipur', area: '14 Acres', soilType: 'Peaty Clay', status: 'Active' },
  { id: 'S-126', name: 'Khasi Hill Slope', location: 'Meghalaya', area: '30 Acres', soilType: 'Lateritic', status: 'Active' },
  { id: 'S-127', name: 'Aizawl Terrace Farm', location: 'Mizoram', area: '12 Acres', soilType: 'Red Loamy', status: 'Active' },
  { id: 'S-128', name: 'Nagaland Forest Plot', location: 'Nagaland', area: '18 Acres', soilType: 'Silty Loam', status: 'Active' },
  { id: 'S-129', name: 'Tripura Rubber Zone', location: 'Tripura', area: '40 Acres', soilType: 'Red Sandy', status: 'Active' },
  { id: 'S-130', name: 'Arunachal Alpine', location: 'Arunachal Pradesh', area: '25 Acres', soilType: 'Mountain Soil', status: 'Inactive' },
  { id: 'S-131', name: 'Jammu Basmati Hub', location: 'Jammu & Kashmir', area: '35 Acres', soilType: 'Alluvial Loam', status: 'Active' },
  { id: 'S-132', name: 'Puducherry Coastal', location: 'Puducherry', area: '5 Acres', soilType: 'Coastal Sandy', status: 'Active' },
  { id: 'S-133', name: 'Kutch Saline Patch', location: 'Gujarat', area: '100 Acres', soilType: 'Saline Arid', status: 'Inactive' },
  { id: 'S-134', name: 'Vidarbha Cotton Site', location: 'Maharashtra', area: '110 Acres', soilType: 'Deep Black', status: 'Active' },
  { id: 'S-135', name: 'Bundelkhand Dryland', location: 'Uttar Pradesh', area: '55 Acres', soilType: 'Red Gravelly', status: 'Active' },
  { id: 'S-136', name: 'Cauvery Delta Plot', location: 'Tamil Nadu', area: '42 Acres', soilType: 'Alluvial Clay', status: 'Active' },
  { id: 'S-137', name: 'Malabar Pepper Farm', location: 'Kerala', area: '20 Acres', soilType: 'Forest Loam', status: 'Active' },
  { id: 'S-138', name: 'Bastar Tribal Lands', location: 'Chhattisgarh', area: '60 Acres', soilType: 'Red Loamy', status: 'Active' },
  { id: 'S-139', name: 'Konkan Mango Orchard', location: 'Maharashtra', area: '30 Acres', soilType: 'Laterite Clay', status: 'Active' },
  { id: 'S-140', name: 'Rayalaseema Scrub', location: 'Andhra Pradesh', area: '70 Acres', soilType: 'Red Sandy', status: 'Active' },
  { id: 'S-141', name: 'Terai Sugarcane Belt', location: 'Uttarakhand', area: '50 Acres', soilType: 'Clayey Loam', status: 'Active' },
  { id: 'S-142', name: 'Brahmaputra Valley B', location: 'Assam', area: '38 Acres', soilType: 'New Alluvial', status: 'Active' },
  { id: 'S-143', name: 'Marathwada Pulses', location: 'Maharashtra', area: '80 Acres', soilType: 'Shallow Black', status: 'Inactive' },
  { id: 'S-144', name: 'Kashmir Saffron Bed', location: 'Jammu & Kashmir', area: '10 Acres', soilType: 'Karewa Soil', status: 'Active' },
  { id: 'S-145', name: 'Bengal Jute Lands', location: 'West Bengal', area: '45 Acres', soilType: 'Silty Alluvial', status: 'Active' },
  { id: 'S-146', name: 'Shimla Apple Zone', location: 'Himachal Pradesh', area: '15 Acres', soilType: 'Podzolic', status: 'Active' },
  { id: 'S-147', name: 'Chittoor Tomato Hub', location: 'Andhra Pradesh', area: '25 Acres', soilType: 'Red Loam', status: 'Active' },
  { id: 'S-148', name: 'Gurdaspur Wheat Plot', location: 'Punjab', area: '55 Acres', soilType: 'Calcareous', status: 'Active' },
  { id: 'S-149', name: 'Mewar Maize Field', location: 'Rajasthan', area: '40 Acres', soilType: 'Mixed Red/Black', status: 'Active' },
  { id: 'S-150', name: 'Coastal Odisha Salt', location: 'Odisha', area: '22 Acres', soilType: 'Saline Clayey', status: 'Inactive' }
];