export const MOCK_USERS = [
  { id: 'U-101', name: 'Arjun Sharma', email: 'arjun.sharma@agrosoil.com', role: 'Admin', status: 'Active' },
  { id: 'U-102', name: 'Meera Patel', email: 'meera.patel@agrosoil.com', role: 'Manager', status: 'Active' },
  { id: 'U-103', name: 'Rahul Verma', email: 'rahul.verma@agrosoil.com', role: 'Technician', status: 'Active' },
  { id: 'U-104', name: 'Priya Singh', email: 'priya.singh@agrosoil.com', role: 'Technician', status: 'Inactive' },
  { id: 'U-105', name: 'Ananya Iyer', email: 'ananya.iyer@agrosoil.com', role: 'Lab Head', status: 'Active' },
  { id: 'U-106', name: 'Rohan Deshmukh', email: 'rohan.d@agrosoil.com', role: 'Field Geologist', status: 'Active' },
  { id: 'U-107', name: 'Siddharth Reddy', email: 'sid.reddy@agrosoil.com', role: 'Manager', status: 'Active' },
  { id: 'U-108', name: 'Ishani Chatterjee', email: 'ishani.c@agrosoil.com', role: 'Pedologist', status: 'Active' },
  { id: 'U-109', name: 'Vikram Malhotra', email: 'vikram.m@agrosoil.com', role: 'Technician', status: 'Active' },
  { id: 'U-110', name: 'Kavita Nair', email: 'kavita.nair@agrosoil.com', role: 'Soil Chemist', status: 'Active' },
  { id: 'U-111', name: 'Aditya Gupta', email: 'aditya.g@agrosoil.com', role: 'Field Supervisor', status: 'Active' },
  { id: 'U-112', name: 'Sneha Kulkarni', email: 'sneha.k@agrosoil.com', role: 'Technician', status: 'Active' },
  { id: 'U-113', name: 'Deepak Yadav', email: 'deepak.y@agrosoil.com', role: 'Admin', status: 'Active' },
  { id: 'U-114', name: 'Tanvi Joshi', email: 'tanvi.j@agrosoil.com', role: 'Lab Assistant', status: 'Active' },
  { id: 'U-115', name: 'Aarav Mukherjee', email: 'aarav.m@agrosoil.com', role: 'Geotechnician', status: 'Active' },
  { id: 'U-116', name: 'Zoya Khan', email: 'zoya.khan@agrosoil.com', role: 'Manager', status: 'Active' },
  { id: 'U-117', name: 'Manish Pandey', email: 'manish.p@agrosoil.com', role: 'Technician', status: 'Inactive' },
  { id: 'U-118', name: 'Ritika Das', email: 'ritika.das@agrosoil.com', role: 'Pedologist', status: 'Active' },
  { id: 'U-119', name: 'Sanjay Rao', email: 'sanjay.rao@agrosoil.com', role: 'Field Geologist', status: 'Active' },
  { id: 'U-120', name: 'Harpreet Kaur', email: 'harpreet.k@agrosoil.com', role: 'Lab Assistant', status: 'Active' },
  { id: 'U-121', name: 'Varun Hegde', email: 'varun.h@agrosoil.com', role: 'Technician', status: 'Active' },
  { id: 'U-122', name: 'Amrita Menon', email: 'amrita.m@agrosoil.com', role: 'Soil Chemist', status: 'Active' },
  { id: 'U-123', name: 'Kartik Shah', email: 'kartik.shah@agrosoil.com', role: 'Manager', status: 'Active' },
  { id: 'U-124', name: 'Bhavna Mishra', email: 'bhavna.m@agrosoil.com', role: 'Technician', status: 'Active' },
  { id: 'U-125', name: 'Pranav Barua', email: 'pranav.b@agrosoil.com', role: 'Field Supervisor', status: 'Active' },
  { id: 'U-126', name: 'Shreya Goswami', email: 'shreya.g@agrosoil.com', role: 'Pedologist', status: 'Active' },
  { id: 'U-127', name: 'Nikhil Saxena', email: 'nikhil.s@agrosoil.com', role: 'Admin', status: 'Active' },
  { id: 'U-128', name: 'Pallavi Bhat', email: 'pallavi.b@agrosoil.com', role: 'Lab Head', status: 'Active' },
  { id: 'U-129', name: 'Abhishek Tiwari', email: 'abhishek.t@agrosoil.com', role: 'Technician', status: 'Active' },
  { id: 'U-130', name: 'Jyoti Kumari', email: 'jyoti.k@agrosoil.com', role: 'Technician', status: 'Inactive' },
  { id: 'U-131', name: 'Sameer Gill', email: 'sameer.gill@agrosoil.com', role: 'Field Geologist', status: 'Active' },
  { id: 'U-132', name: 'Divya Rangan', email: 'divya.r@agrosoil.com', role: 'Soil Chemist', status: 'Active' },
  { id: 'U-133', name: 'Yash Vardhan', email: 'yash.v@agrosoil.com', role: 'Manager', status: 'Active' },
  { id: 'U-134', name: 'Meghna Roy', email: 'meghna.roy@agrosoil.com', role: 'Lab Assistant', status: 'Active' },
  { id: 'U-135', name: 'Kunal Mehra', email: 'kunal.m@agrosoil.com', role: 'Technician', status: 'Active' },
  { id: 'U-136', name: 'Trupti Patil', email: 'trupti.patil@agrosoil.com', role: 'Pedologist', status: 'Active' },
  { id: 'U-137', name: 'Gaurav Bisht', email: 'gaurav.b@agrosoil.com', role: 'Field Supervisor', status: 'Active' },
  { id: 'U-138', name: 'Suhana Parveen', email: 'suhana.p@agrosoil.com', role: 'Lab Head', status: 'Active' },
  { id: 'U-139', name: 'Akash Dwivedi', email: 'akash.d@agrosoil.com', role: 'Admin', status: 'Active' },
  { id: 'U-140', name: 'Swati Shinde', email: 'swati.s@agrosoil.com', role: 'Technician', status: 'Active' },
  { id: 'U-141', name: 'Uday Kiran', email: 'uday.k@agrosoil.com', role: 'Geotechnician', status: 'Active' },
  { id: 'U-142', name: 'Nandini Prasad', email: 'nandini.p@agrosoil.com', role: 'Soil Chemist', status: 'Active' },
  { id: 'U-143', name: 'Rishi Kapoor', email: 'rishi.k@agrosoil.com', role: 'Manager', status: 'Inactive' },
  { id: 'U-144', name: 'Preeti Choudhury', email: 'preeti.c@agrosoil.com', role: 'Technician', status: 'Active' },
  { id: 'U-145', name: 'Mohit Agarwal', email: 'mohit.a@agrosoil.com', role: 'Pedologist', status: 'Active' },
  { id: 'U-146', name: 'Arpita Jena', email: 'arpita.jena@agrosoil.com', role: 'Lab Assistant', status: 'Active' },
  { id: 'U-147', name: 'Rajesh Solanki', email: 'rajesh.s@agrosoil.com', role: 'Field Supervisor', status: 'Active' },
  { id: 'U-148', name: 'Kiran Thapa', email: 'kiran.t@agrosoil.com', role: 'Technician', status: 'Active' },
  { id: 'U-149', name: 'Indrani Bose', email: 'indrani.b@agrosoil.com', role: 'Lab Head', status: 'Active' },
  { id: 'U-150', name: 'Sahil Varma', email: 'sahil.v@agrosoil.com', role: 'Technician', status: 'Active' }
];