export const MOCK_TESTS = [
    // JANUARY
  { id: 'T-001', site: 'Green Valley Farm', testType: 'pH Test', resultValue: 6.8, unit: 'pH', date: '2026-01-05', status: 'Completed' },
  { id: 'T-002', site: 'Sunrise Agro Fields', testType: 'Nitrogen Test', resultValue: 82, unit: 'ppm', date: '2026-01-08', status: 'Completed' },
  { id: 'T-003', site: 'Riverbank Plantation', testType: 'Phosphorus Test', resultValue: 38, unit: 'ppm', date: '2026-01-12', status: 'Completed' },
  { id: 'T-004', site: 'Green Valley Farm', testType: 'Organic Carbon', resultValue: 0.75, unit: '%', date: '2026-01-15', status: 'Completed' },
  { id: 'T-005', site: 'Eastern Harvest Land', testType: 'Potassium Test', resultValue: 140, unit: 'ppm', date: '2026-01-20', status: 'Pending' },
  { id: 'T-006', site: 'Coastal Palm Grove', testType: 'pH Test', resultValue: 7.1, unit: 'pH', date: '2026-01-25', status: 'Completed' },

  // FEBRUARY
  { id: 'T-007', site: 'Green Valley Farm', testType: 'Nitrogen Test', resultValue: 95, unit: 'ppm', date: '2026-02-02', status: 'Completed' },
  { id: 'T-008', site: 'Odisha Paddy Fields', testType: 'pH Test', resultValue: 6.4, unit: 'pH', date: '2026-02-06', status: 'Completed' },
  { id: 'T-009', site: 'Sunrise Agro Fields', testType: 'Potassium Test', resultValue: 160, unit: 'ppm', date: '2026-02-10', status: 'Completed' },
  { id: 'T-010', site: 'Riverbank Plantation', testType: 'Organic Carbon', resultValue: 0.92, unit: '%', date: '2026-02-14', status: 'Completed' },
  { id: 'T-011', site: 'Eastern Harvest Land', testType: 'Phosphorus Test', resultValue: 44, unit: 'ppm', date: '2026-02-18', status: 'Completed' },
  { id: 'T-012', site: 'Green Valley Farm', testType: 'pH Test', resultValue: 6.9, unit: 'pH', date: '2026-02-23', status: 'Completed' },

  // MARCH
  { id: 'T-013', site: 'Imphal Valley Farm', testType: 'Nitrogen Test', resultValue: 70, unit: 'ppm', date: '2026-03-03', status: 'Completed' },
  { id: 'T-014', site: 'Tripura Rubber Zone', testType: 'Organic Carbon', resultValue: 1.1, unit: '%', date: '2026-03-07', status: 'Completed' },
  { id: 'T-015', site: 'Green Valley Farm', testType: 'Phosphorus Test', resultValue: 52, unit: 'ppm', date: '2026-03-11', status: 'Completed' },
  { id: 'T-016', site: 'Coastal Palm Grove', testType: 'Potassium Test', resultValue: 175, unit: 'ppm', date: '2026-03-15', status: 'Completed' },
  { id: 'T-017', site: 'Godavari Basin North', testType: 'pH Test', resultValue: 7.3, unit: 'pH', date: '2026-03-20', status: 'Completed' },
  { id: 'T-018', site: 'Sunrise Agro Fields', testType: 'Nitrogen Test', resultValue: 88, unit: 'ppm', date: '2026-03-25', status: 'Pending' },

  // APRIL
  { id: 'T-019', site: 'Green Valley Farm', testType: 'Potassium Test', resultValue: 150, unit: 'ppm', date: '2026-04-04', status: 'Completed' },
  { id: 'T-020', site: 'Riverbank Plantation', testType: 'pH Test', resultValue: 6.5, unit: 'pH', date: '2026-04-08', status: 'Completed' },
  { id: 'T-021', site: 'Eastern Harvest Land', testType: 'Organic Carbon', resultValue: 0.84, unit: '%', date: '2026-04-12', status: 'Completed' },
  { id: 'T-022', site: 'Odisha Paddy Fields', testType: 'Phosphorus Test', resultValue: 47, unit: 'ppm', date: '2026-04-18', status: 'Completed' },
  { id: 'T-023', site: 'Imphal Valley Farm', testType: 'Nitrogen Test', resultValue: 76, unit: 'ppm', date: '2026-04-22', status: 'Completed' },
  { id: 'T-024', site: 'Tripura Rubber Zone', testType: 'pH Test', resultValue: 6.7, unit: 'pH', date: '2026-04-26', status: 'Completed' },

  // MAY
  { id: 'T-025', site: 'Green Valley Farm', testType: 'Nitrogen Test', resultValue: 102, unit: 'ppm', date: '2026-05-02', status: 'Completed' },
  { id: 'T-026', site: 'Sunrise Agro Fields', testType: 'Phosphorus Test', resultValue: 41, unit: 'ppm', date: '2026-05-06', status: 'Completed' },
  { id: 'T-027', site: 'Riverbank Plantation', testType: 'Potassium Test', resultValue: 165, unit: 'ppm', date: '2026-05-10', status: 'Completed' },
  { id: 'T-028', site: 'Godavari Basin North', testType: 'Organic Carbon', resultValue: 0.97, unit: '%', date: '2026-05-14', status: 'Completed' },
  { id: 'T-029', site: 'Eastern Harvest Land', testType: 'pH Test', resultValue: 6.3, unit: 'pH', date: '2026-05-18', status: 'Completed' },
  { id: 'T-030', site: 'Coastal Palm Grove', testType: 'Nitrogen Test', resultValue: 90, unit: 'ppm', date: '2026-05-22', status: 'Pending' },

  // JUNE
  { id: 'T-031', site: 'Green Valley Farm', testType: 'Phosphorus Test', resultValue: 50, unit: 'ppm', date: '2026-06-03', status: 'Completed' },
  { id: 'T-032', site: 'Odisha Paddy Fields', testType: 'Potassium Test', resultValue: 180, unit: 'ppm', date: '2026-06-07', status: 'Completed' },
  { id: 'T-033', site: 'Imphal Valley Farm', testType: 'Organic Carbon', resultValue: 1.05, unit: '%', date: '2026-06-11', status: 'Completed' },
  { id: 'T-034', site: 'Tripura Rubber Zone', testType: 'Nitrogen Test', resultValue: 85, unit: 'ppm', date: '2026-06-15', status: 'Completed' },
  { id: 'T-035', site: 'Riverbank Plantation', testType: 'pH Test', resultValue: 6.6, unit: 'pH', date: '2026-06-19', status: 'Completed' },
  { id: 'T-036', site: 'Sunrise Agro Fields', testType: 'Organic Carbon', resultValue: 0.89, unit: '%', date: '2026-06-23', status: 'Completed' },

  // EXTRA VARIATION
  { id: 'T-037', site: 'Green Valley Farm', testType: 'Organic Carbon', resultValue: 0.78, unit: '%', date: '2026-02-03', status: 'Completed' },
  { id: 'T-038', site: 'Green Valley Farm', testType: 'Nitrogen Test', resultValue: 99, unit: 'ppm', date: '2026-03-14', status: 'Completed' },
  { id: 'T-039', site: 'Green Valley Farm', testType: 'Potassium Test', resultValue: 170, unit: 'ppm', date: '2026-05-17', status: 'Completed' },
  { id: 'T-040', site: 'Sunrise Agro Fields', testType: 'pH Test', resultValue: 6.9, unit: 'pH', date: '2026-04-09', status: 'Completed' },
  { id: 'T-041', site: 'Sunrise Agro Fields', testType: 'Nitrogen Test', resultValue: 92, unit: 'ppm', date: '2026-06-02', status: 'Completed' },
  { id: 'T-042', site: 'Riverbank Plantation', testType: 'Phosphorus Test', resultValue: 49, unit: 'ppm', date: '2026-01-28', status: 'Completed' },
  { id: 'T-043', site: 'Riverbank Plantation', testType: 'Nitrogen Test', resultValue: 74, unit: 'ppm', date: '2026-04-16', status: 'Completed' },
  { id: 'T-044', site: 'Eastern Harvest Land', testType: 'Potassium Test', resultValue: 155, unit: 'ppm', date: '2026-05-30', status: 'Completed' },
  { id: 'T-045', site: 'Coastal Palm Grove', testType: 'Organic Carbon', resultValue: 1.02, unit: '%', date: '2026-03-09', status: 'Completed' },
  { id: 'T-046', site: 'Godavari Basin North', testType: 'pH Test', resultValue: 7.0, unit: 'pH', date: '2026-06-21', status: 'Completed' },
  { id: 'T-047', site: 'Imphal Valley Farm', testType: 'Potassium Test', resultValue: 168, unit: 'ppm', date: '2026-02-19', status: 'Completed' },
  { id: 'T-048', site: 'Tripura Rubber Zone', testType: 'Phosphorus Test', resultValue: 46, unit: 'ppm', date: '2026-03-30', status: 'Completed' },
  { id: 'T-049', site: 'Green Valley Farm', testType: 'pH Test', resultValue: 6.4, unit: 'pH', date: '2026-06-28', status: 'Completed' },
  { id: 'T-050', site: 'Odisha Paddy Fields', testType: 'Nitrogen Test', resultValue: 83, unit: 'ppm', date: '2026-05-11', status: 'Completed' },
  { id: 'T-201', site: 'Green Valley Farm', testType: 'pH Test', resultValue: 6.8, unit: 'pH', date: '2026-02-10', status: 'Completed' },
  { id: 'T-202', site: 'Sunrise Agro Fields', testType: 'Nitrogen Test', resultValue: 85, unit: 'ppm', date: '2026-02-09', status: 'Completed' },
  { id: 'T-203', site: 'Riverbank Plantation', testType: 'Phosphorus Test', resultValue: 42, unit: 'ppm', date: '2026-02-08', status: 'Completed' },
  { id: 'T-204', site: 'Highland Crop Zone', testType: 'Potassium Test', resultValue: 155, unit: 'ppm', date: '2026-02-07', status: 'Pending' },
  { id: 'T-205', site: 'Eastern Harvest Land', testType: 'Organic Carbon', resultValue: 0.85, unit: '%', date: '2026-02-05', status: 'Completed' },
  { id: 'T-206', site: 'Deccan Black Soil Hub', testType: 'pH Test', resultValue: 7.9, unit: 'pH', date: '2026-02-11', status: 'Completed' },
  { id: 'T-207', site: 'Thar Edge Cultivation', testType: 'Nitrogen Test', resultValue: 32, unit: 'ppm', date: '2026-02-12', status: 'Completed' },
  { id: 'T-208', site: 'Nilgiri Tea Estates', testType: 'Organic Carbon', resultValue: 1.42, unit: '%', date: '2026-02-10', status: 'Completed' },
  { id: 'T-209', site: 'Coastal Palm Grove', testType: 'Potassium Test', resultValue: 180, unit: 'ppm', date: '2026-02-13', status: 'In Progress' },
  { id: 'T-210', site: 'Brahmaputra Silt Farm', testType: 'Phosphorus Test', resultValue: 55, unit: 'ppm', date: '2026-02-09', status: 'Completed' },
  { id: 'T-211', site: 'Gujarat Cotton Belt', testType: 'pH Test', resultValue: 8.2, unit: 'pH', date: '2026-02-08', status: 'Completed' },
  { id: 'T-212', site: 'Telangana Drylands', testType: 'Nitrogen Test', resultValue: 45, unit: 'ppm', date: '2026-02-07', status: 'Completed' },
  { id: 'T-213', site: 'Odisha Paddy Fields', testType: 'Organic Carbon', resultValue: 0.65, unit: '%', date: '2026-02-06', status: 'Completed' },
  { id: 'T-214', site: 'Chhota Nagpur Plot', testType: 'Phosphorus Test', resultValue: 18, unit: 'ppm', date: '2026-02-05', status: 'Completed' },
  { id: 'T-215', site: 'Himalayan Orchard', testType: 'Potassium Test', resultValue: 75, unit: 'ppm', date: '2026-02-04', status: 'Completed' },
  { id: 'T-216', site: 'Doon Valley Acres', testType: 'pH Test', resultValue: 6.2, unit: 'pH', date: '2026-02-14', status: 'Pending' },
  { id: 'T-217', site: 'Sundarban Delta Edge', testType: 'Nitrogen Test', resultValue: 110, unit: 'ppm', date: '2026-02-13', status: 'Completed' },
  { id: 'T-218', site: 'Malwa Plateau Site', testType: 'Organic Carbon', resultValue: 0.45, unit: '%', date: '2026-02-12', status: 'Completed' },
  { id: 'T-219', site: 'Mysuru Silk Farms', testType: 'Potassium Test', resultValue: 140, unit: 'ppm', date: '2026-02-11', status: 'Completed' },
  { id: 'T-220', site: 'Zanskar Alpine Plot', testType: 'pH Test', resultValue: 5.8, unit: 'pH', date: '2026-02-10', status: 'Completed' },
  { id: 'T-221', site: 'Godavari Basin North', testType: 'Nitrogen Test', resultValue: 95, unit: 'ppm', date: '2026-02-09', status: 'Completed' },
  { id: 'T-222', site: 'Raipur Plain Zone', testType: 'Phosphorus Test', resultValue: 38, unit: 'ppm', date: '2026-02-08', status: 'Completed' },
  { id: 'T-223', site: 'Goan Cashew Hills', testType: 'Organic Carbon', resultValue: 1.15, unit: '%', date: '2026-02-07', status: 'Completed' },
  { id: 'T-224', site: 'Sikkim Organic Site', testType: 'Potassium Test', resultValue: 195, unit: 'ppm', date: '2026-02-06', status: 'Completed' },
  { id: 'T-225', site: 'Imphal Valley Farm', testType: 'pH Test', resultValue: 6.5, unit: 'pH', date: '2026-02-05', status: 'Completed' },
  { id: 'T-226', site: 'Khasi Hill Slope', testType: 'Nitrogen Test', resultValue: 58, unit: 'ppm', date: '2026-02-04', status: 'In Progress' },
  { id: 'T-227', site: 'Aizawl Terrace Farm', testType: 'Organic Carbon', resultValue: 1.25, unit: '%', date: '2026-02-03', status: 'Completed' },
  { id: 'T-228', site: 'Nagaland Forest Plot', testType: 'Phosphorus Test', resultValue: 22, unit: 'ppm', date: '2026-02-02', status: 'Completed' },
  { id: 'T-229', site: 'Tripura Rubber Zone', testType: 'Potassium Test', resultValue: 88, unit: 'ppm', date: '2026-02-01', status: 'Completed' },
  { id: 'T-230', site: 'Arunachal Alpine', testType: 'pH Test', resultValue: 5.6, unit: 'pH', date: '2026-01-31', status: 'Completed' },
  { id: 'T-231', site: 'Jammu Basmati Hub', testType: 'Nitrogen Test', resultValue: 72, unit: 'ppm', date: '2026-02-14', status: 'Pending' },
  { id: 'T-232', site: 'Puducherry Coastal', testType: 'Organic Carbon', resultValue: 0.35, unit: '%', date: '2026-02-13', status: 'Completed' },
  { id: 'T-233', site: 'Kutch Saline Patch', testType: 'pH Test', resultValue: 8.4, unit: 'pH', date: '2026-02-12', status: 'Completed' },
  { id: 'T-234', site: 'Vidarbha Cotton Site', testType: 'Potassium Test', resultValue: 115, unit: 'ppm', date: '2026-02-11', status: 'Completed' },
  { id: 'T-235', site: 'Bundelkhand Dryland', testType: 'Nitrogen Test', resultValue: 25, unit: 'ppm', date: '2026-02-10', status: 'Completed' },
  { id: 'T-236', site: 'Cauvery Delta Plot', testType: 'Phosphorus Test', resultValue: 48, unit: 'ppm', date: '2026-02-09', status: 'Completed' },
  { id: 'T-237', site: 'Malabar Pepper Farm', testType: 'Organic Carbon', resultValue: 1.38, unit: '%', date: '2026-02-08', status: 'Completed' },
  { id: 'T-238', site: 'Bastar Tribal Lands', testType: 'Potassium Test', resultValue: 62, unit: 'ppm', date: '2026-02-07', status: 'Completed' },
  { id: 'T-239', site: 'Konkan Mango Orchard', testType: 'pH Test', resultValue: 6.1, unit: 'pH', date: '2026-02-06', status: 'Completed' },
  { id: 'T-240', site: 'Rayalaseema Scrub', testType: 'Nitrogen Test', resultValue: 39, unit: 'ppm', date: '2026-02-05', status: 'Completed' },
  { id: 'T-241', site: 'Terai Sugarcane Belt', testType: 'Phosphorus Test', resultValue: 52, unit: 'ppm', date: '2026-02-04', status: 'Completed' },
  { id: 'T-242', site: 'Brahmaputra Valley B', testType: 'Organic Carbon', resultValue: 0.92, unit: '%', date: '2026-02-03', status: 'Completed' },
  { id: 'T-243', site: 'Marathwada Pulses', testType: 'Potassium Test', resultValue: 175, unit: 'ppm', date: '2026-02-02', status: 'Completed' },
  { id: 'T-244', site: 'Kashmir Saffron Bed', testType: 'pH Test', resultValue: 7.4, unit: 'pH', date: '2026-02-01', status: 'Completed' },
  { id: 'T-245', site: 'Bengal Jute Lands', testType: 'Nitrogen Test', resultValue: 105, unit: 'ppm', date: '2026-01-31', status: 'Completed' },
  { id: 'T-246', site: 'Shimla Apple Zone', testType: 'Organic Carbon', resultValue: 1.10, unit: '%', date: '2026-02-14', status: 'In Progress' },
  { id: 'T-247', site: 'Chittoor Tomato Hub', testType: 'Phosphorus Test', resultValue: 28, unit: 'ppm', date: '2026-02-13', status: 'Completed' },
  { id: 'T-248', site: 'Gurdaspur Wheat Plot', testType: 'Potassium Test', resultValue: 92, unit: 'ppm', date: '2026-02-12', status: 'Completed' },
  { id: 'T-249', site: 'Mewar Maize Field', testType: 'pH Test', resultValue: 7.2, unit: 'pH', date: '2026-02-11', status: 'Completed' },
  { id: 'T-250', site: 'Coastal Odisha Salt', testType: 'Organic Carbon', resultValue: 0.40, unit: '%', date: '2026-02-10', status: 'Completed' }
];